# Generated by Django 4.1.7 on 2023-03-30 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                (
                    "common_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "rare_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "epic_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "legendary_probability",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("price", models.IntegerField()),
            ],
        ),
    ]
