# Generated by Django 4.1.7 on 2023-03-27 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("buyed_id", models.CharField(max_length=150)),
                ("seller_id", models.CharField(max_length=150)),
            ],
        ),
    ]
