# Generated by Django 4.1.7 on 2023-03-28 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_transaction_seller_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="pokemon_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
