# Generated by Django 4.1.7 on 2023-03-24 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemons",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=36)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("C", "common"),
                            ("R", "rare"),
                            ("E", "epic"),
                            ("L", "legendary"),
                        ],
                        max_length=36,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "type01",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("fire", "fire"),
                            ("water", "water"),
                            ("grass", "grass"),
                            ("electric", "electric"),
                            ("ice", "ice"),
                            ("fighting", "fighting"),
                            ("poison", "poison"),
                            ("ground", "ground"),
                            ("flying", "flying"),
                            ("psychic", "psychic"),
                            ("bug", "bug"),
                            ("rock", "rock"),
                            ("ghost", "ghost"),
                            ("dark", "dark"),
                            ("dragon", "dragon"),
                            ("steel", "steel"),
                            ("fairy", "fairy"),
                        ],
                        max_length=36,
                    ),
                ),
                (
                    "type02",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("fire", "fire"),
                            ("water", "water"),
                            ("grass", "grass"),
                            ("electric", "electric"),
                            ("ice", "ice"),
                            ("fighting", "fighting"),
                            ("poison", "poison"),
                            ("ground", "ground"),
                            ("flying", "flying"),
                            ("psychic", "psychic"),
                            ("bug", "bug"),
                            ("rock", "rock"),
                            ("ghost", "ghost"),
                            ("dark", "dark"),
                            ("dragon", "dragon"),
                            ("steel", "steel"),
                            ("fairy", "fairy"),
                        ],
                        max_length=36,
                        null=True,
                    ),
                ),
                ("price", models.IntegerField(default=0)),
            ],
        ),
    ]
